<?php

namespace Emion\RegisterBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
  public function getNumberBooks() {
    return $this
      ->createQueryBuilder('id')
      ->select('COUNT(id)')
      ->getQuery()
      ->getSingleScalarResult()
    ;
  }
}
