<?php

namespace Emion\RegisterBundle\Repository;

/**
 * NPCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NPCRepository extends \Doctrine\ORM\EntityRepository
{
  public function getNumberNPC() {
    return $this
      ->createQueryBuilder('id')
      ->select('COUNT(id)')
      ->getQuery()
      ->getSingleScalarResult()
    ;
  }
}
